package security

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
)

// GenerateRefreshToken returns a cryptographically random, URL-safe opaque
// token (not a JWT — deliberately). 32 bytes of crypto/rand entropy is 256
// bits, far beyond brute-force range.
//
// Why opaque instead of a second JWT? A refresh token's only job is "prove
// you're still you, so I'll issue a new access token" — it doesn't need to
// carry claims, doesn't need to be self-verifying offline, and critically,
// unlike a JWT, an opaque token is meaningless without a database lookup.
// That's a feature here: it's what makes revocation possible at all. A
// stateless JWT refresh token can't be revoked before its expiry without
// maintaining a blocklist anyway — at which point you've reinvented this
// exact table with extra steps.
func GenerateRefreshToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("security: generating refresh token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// HashToken returns the SHA-256 hex digest of a raw token, for storage.
//
// Note this is a plain fast hash (SHA-256), not Argon2id like passwords.
// That's intentional, not an inconsistency: Argon2id's expense defends
// against brute-forcing a *low-entropy, human-chosen* secret (a password).
// A refresh token is 256 bits of pure random entropy generated by us —
// brute-forcing it is already computationally infeasible regardless of
// hash speed, so a fast cryptographic hash is the right tool: we want quick
// lookups on every refresh request, not deliberately slow ones.
func HashToken(raw string) string {
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:])
}
